<?php

namespace OC\AppFramework\Middleware\PublicShare;

use OC\AppFramework\Middleware\PublicShare\Exceptions\NeedAuthenticationException;
use OCP\AppFramework\Http\NotFoundResponse;
use OCP\AppFramework\Http\Response;
use OCP\AppFramework\Middleware;
use OCP\AppFramework\PublicShareController;
use OCP\Files\NotFoundException;
use OCP\IRequest;
use OCP\ISession;

class PublicShareMiddleware extends Middleware {
	/** @var IRequest */
	private $request;

	/** @var ISession */
	private $session;

	public function __construct(IRequest $request, ISession $session) {
		$this->request = $request;
		$this->session = $session;
	}

	public function beforeController($controller, $methodName) {
		if (!($controller instanceof PublicShareController)) {
			return;
		}

		// We require the token parameter to be set
		$token = $this->request->getParam('token');
		if ($token === null) {
			throw new NotFoundException();
		}

		// No need to check for authentication when we try to authenticate
		if ($methodName === 'authenticate' || $methodName === 'showAuthenticate') {
			return;
		}

		// If authentication succeeds just continue
		if ($controller->isAuthenticated($token)) {
			return;
		}

		// We need to authenticate
		$this->session->set('public_link_authenticate_redirect', json_encode($this->request->getParams()));
		throw new NeedAuthenticationException();

	}

	public function afterException($controller, $methodName, \Exception $exception) {
		if (!($controller instanceof PublicShareController)) {
			throw $exception;
		}

		if ($exception instanceof NotFoundException) {
			return new NotFoundResponse();
		}

		if ($exception instanceof NeedAuthenticationException) {
			$token = $this->request->getParam('token');
			return $controller->getAuthenticationRedirect($token, $this->getFunctionForRoute($this->request->getParam('_route')));
		}

		throw $exception;
	}

	public function afterController($controller, $methodName, Response $response) {
		return parent::afterController($controller, $methodName, $response); // TODO: Change the autogenerated stub
	}

	public function beforeOutput($controller, $methodName, $output) {
		return parent::beforeOutput($controller, $methodName, $output); // TODO: Change the autogenerated stub
	}

	private function getFunctionForRoute(string $route): string {
		return array_pop(explode('.', $route));
	}
}
